### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by arvl130** [arvl130/expense-tracker#1]
Here are a bunch of tasks we need to get done in order to make this app usable:

- [x] Implement transaction deletion
- [x] Implement transaction editing
- [x] Implement receipt editing
- [ ] Add a homepage?
- [ ] Import/export transactions
- [ ] ...
